export const PRODUCT_LIST_FETCHING = "PRODUCT_LIST_FETCHING";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";


export const CART_LIST = "CART_LIST"
export const ADD_CART = "ADD_CART"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const CART_INCREASE_ORDER = "CART_INCREASE_ORDER"
export const CART_DECREASE_ORDER = "CART_DECREASE_ORDER"
export const CART_FILTER_DUPLICATE = "CART_FILTER_DUPLICATE" 


export const INITIAL_VALUES = "INITIAL_VALUES"
export const ORDERED_VALUE = "ORDERED_VALUE"
export const INCREASE_ORDER = "INCREASE_ORDER"
export const DECREASE_ORDER = "DECREASE_ORDER"
export const RESET_ORDER = "RESET_ORDER"


export const FILTER_DATA = "FILTER_DATA"
export const RESET_FILTER_DATA = "RESET_FILTER_DATA"